<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Audit Log</title>
    <style>
        /* Same letterhead technique as pdf/dispatch-log.blade.php. */
        @page {
            size: legal portrait;
            margin: 1.55in 0.9in 1.65in 1.3in;
        }

        .letterhead-bg {
            position: fixed;
            top: -1.55in;
            left: -1.3in;
            width: 8.5in;
            height: 14in;
            z-index: -1;
        }
        .letterhead-bg img {
            width: 100%;
            height: 100%;
        }

        body {
            font-family: 'Helvetica', Arial, sans-serif;
            color: #1a1a1a;
            font-size: 10.5px;
            margin: 0;
            padding: 0;
        }

        .header {
            width: 100%;
            padding-bottom: 8px;
            margin-bottom: 10px;
            border-bottom: 1px solid #d5d5db;
        }
        .header td { vertical-align: top; }
        .doc-title {
            font-size: 14px;
            font-weight: bold;
            color: #1a1a2e;
        }
        .doc-subtitle {
            font-size: 9.5px;
            color: #666666;
            margin-top: 2px;
        }
        .meta {
            text-align: right;
            font-size: 9.5px;
            color: #444444;
        }
        .meta strong { color: #1a1a1a; }

        table.log-table {
            width: 100%;
            border-collapse: collapse;
        }
        table.log-table th {
            background-color: #f0f0f3;
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            color: #444444;
        }
        table.log-table td {
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            font-size: 9.5px;
            background-color: #ffffff;
            vertical-align: top;
        }
        table.log-table tr:nth-child(even) td {
            background-color: #fafafa;
        }
        .channel-web { color: #1a4d8f; font-weight: bold; }
        .channel-rfid { color: #0a7a3d; font-weight: bold; }
        .channel-scheduler { color: #a35b00; font-weight: bold; }

        .empty-note {
            font-size: 10px;
            color: #888888;
            font-style: italic;
            padding: 8px 0;
        }

        .summary {
            margin-top: 16px;
            font-size: 9.5px;
            color: #444444;
            border-top: 1px solid #d5d5db;
            padding-top: 8px;
        }
        .signatures {
            width: 100%;
            margin-top: 36px;
            border-collapse: collapse;
        }
        .signatures td {
            width: 50%;
            text-align: center;
            font-size: 9px;
            color: #444444;
            padding-top: 28px;
        }
        .signature-line {
            border-top: 1px solid #888888;
            width: 80%;
            margin: 0 auto 4px auto;
        }
    </style>
</head>
<body>

    <div class="letterhead-bg">
        <img src="{{ public_path('images/pdf-bg.jpg') }}" alt="">
    </div>

    <table class="header">
        <tr>
            <td>
                <div class="doc-title">Audit Log</div>
                <div class="doc-subtitle">System events &amp; user actions</div>
            </td>
            <td class="meta">
                <div>
                    <strong>Period:</strong>
                    @if ($from && $to)
                        {{ $from->format('M d, Y') }}
                        @if (!$from->isSameDay($to))
                            &ndash; {{ $to->format('M d, Y') }}
                        @endif
                    @else
                        All time
                    @endif
                </div>
                @if (!empty($scopeNote))
                    <div><strong>Filters:</strong> {{ $scopeNote }}</div>
                @endif
                <div><strong>Generated by:</strong> {{ $generatedBy }}</div>
                <div><strong>Generated on:</strong> {{ $generatedAt->format('M d, Y g:i A') }}</div>
            </td>
        </tr>
    </table>

    @if ($logs->isEmpty())
        <p class="empty-note">No audit log entries matched the selected filters.</p>
    @else
        <table class="log-table">
            <thead>
                <tr>
                    <th style="width: 16%;">Date &amp; Time</th>
                    <th style="width: 16%;">Actor</th>
                    <th style="width: 14%;">Action</th>
                    <th style="width: 42%;">Subject</th>
                    <th style="width: 12%;">Channel</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($logs as $log)
                    <tr>
                        <td>{{ $log->created_at->format('M d, Y g:i A') }}</td>
                        <td>{{ $log->user?->name ?? 'System' }}</td>
                        <td>{{ $log->action }}</td>
                        <td>{{ $log->subject }}</td>
                        <td>
                            @php
                                $channelClass = match (strtolower($log->channel)) {
                                    'web'       => 'channel-web',
                                    'rfid'      => 'channel-rfid',
                                    'scheduler' => 'channel-scheduler',
                                    default     => '',
                                };
                            @endphp
                            <span class="{{ $channelClass }}">{{ $log->channel }}</span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="summary">
        <strong>Total entries:</strong> {{ $totalCount }}
    </div>

    <table class="signatures">
        <tr>
            <td>
                <div class="signature-line"></div>
                Prepared by
            </td>
            <td>
                <div class="signature-line"></div>
                Verified by
            </td>
        </tr>
    </table>

</body>
</html>
