<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Card Statement</title>
    <style>
        /* Same letterhead technique as pdf/dispatch-log.blade.php. */
        @page {
            size: legal portrait;
            margin: 1.55in 0.9in 1.65in 1.3in;
        }

        .letterhead-bg {
            position: fixed;
            top: -1.55in;
            left: -1.3in;
            width: 8.5in;
            height: 14in;
            z-index: -1;
        }
        .letterhead-bg img {
            width: 100%;
            height: 100%;
        }

        body {
            font-family: 'Helvetica', Arial, sans-serif;
            color: #1a1a1a;
            font-size: 10.5px;
            margin: 0;
            padding: 0;
        }

        .header {
            width: 100%;
            padding-bottom: 8px;
            margin-bottom: 10px;
            border-bottom: 1px solid #d5d5db;
        }
        .header td { vertical-align: top; }
        .doc-title {
            font-size: 14px;
            font-weight: bold;
            color: #1a1a2e;
        }
        .doc-subtitle {
            font-size: 9.5px;
            color: #666666;
            margin-top: 2px;
        }
        .meta {
            text-align: right;
            font-size: 9.5px;
            color: #444444;
        }
        .meta strong { color: #1a1a1a; }

        .cardholder-block {
            margin-bottom: 12px;
            font-size: 10px;
        }
        .cardholder-block strong { color: #1a1a1a; }

        table.txn-table {
            width: 100%;
            border-collapse: collapse;
        }
        table.txn-table th {
            background-color: #f0f0f3;
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            color: #444444;
        }
        table.txn-table td {
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            font-size: 9.5px;
            background-color: #ffffff;
            vertical-align: top;
        }
        table.txn-table tr:nth-child(even) td {
            background-color: #fafafa;
        }
        .amount-cell { text-align: right; }
        .status-success { color: #0a7a3d; font-weight: bold; }
        .status-failed { color: #b3261e; font-weight: bold; }
        .status-insufficient_balance { color: #a35b00; font-weight: bold; }

        .empty-note {
            font-size: 10px;
            color: #888888;
            font-style: italic;
            padding: 8px 0;
        }

        .summary {
            margin-top: 16px;
            font-size: 9.5px;
            color: #444444;
            border-top: 1px solid #d5d5db;
            padding-top: 8px;
        }
    </style>
</head>
<body>

    <div class="letterhead-bg">
        <img src="{{ public_path('images/pdf-bg.jpg') }}" alt="">
    </div>

    <table class="header">
        <tr>
            <td>
                <div class="doc-title">Card Statement</div>
                <div class="doc-subtitle">Full transaction history for this card</div>
            </td>
            <td class="meta">
                <div><strong>Generated by:</strong> {{ $generatedBy }}</div>
                <div><strong>Generated on:</strong> {{ $generatedAt->format('M d, Y g:i A') }}</div>
            </td>
        </tr>
    </table>

    <div class="cardholder-block">
        <div><strong>Cardholder:</strong> {{ $cardholder->name }} ({{ $cardholder->user_code }})</div>
        <div><strong>Card number:</strong> {{ $cardholder->card->card_number }}</div>
        <div><strong>Current balance:</strong> &#8369;{{ number_format($closingBalance, 2) }}</div>
    </div>

    @if ($transactions->isEmpty())
        <p class="empty-note">No transactions on file for this card.</p>
    @else
        <table class="txn-table">
            <thead>
                <tr>
                    <th style="width: 16%;">Date &amp; Time</th>
                    <th style="width: 12%;">Type</th>
                    <th style="width: 12%;">Source</th>
                    <th style="width: 14%;">Reference No.</th>
                    <th style="width: 13%;">Amount</th>
                    <th style="width: 13%;">Balance After</th>
                    <th style="width: 10%;">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transactions as $transaction)
                    <tr>
                        <td>{{ $transaction->transaction_time?->format('M d, Y g:i A') ?? '—' }}</td>
                        <td>{{ ucfirst($transaction->transaction_type ?? '—') }}</td>
                        <td>{{ $transaction->source ?? '—' }}</td>
                        <td>{{ $transaction->reference_no }}</td>
                        <td class="amount-cell">&#8369;{{ number_format($transaction->amount, 2) }}</td>
                        <td class="amount-cell">&#8369;{{ number_format($transaction->balance_after, 2) }}</td>
                        <td>
                            <span class="status-{{ $transaction->status }}">
                                {{ str($transaction->status)->replace('_', ' ')->ucfirst() }}
                            </span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="summary">
        <strong>Total transactions:</strong> {{ $transactions->count() }}
    </div>

</body>
</html>
