<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Card Inventory</title>
    <style>
        @include('pdf.partials.letterhead-style')

        body {
            font-family: 'Helvetica', Arial, sans-serif;
            color: #1a1a1a;
            font-size: 10.5px;
            margin: 0;
            padding: 0;
        }

        .header {
            width: 100%;
            padding-bottom: 8px;
            margin-bottom: 10px;
            border-bottom: 1px solid #d5d5db;
        }
        .header td { vertical-align: top; }
        .doc-title {
            font-size: 14px;
            font-weight: bold;
            color: #1a1a2e;
        }
        .doc-subtitle {
            font-size: 9.5px;
            color: #666666;
            margin-top: 2px;
        }
        .meta {
            text-align: right;
            font-size: 9.5px;
            color: #444444;
        }
        .meta strong { color: #1a1a1a; }

        table.stats-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 12px;
        }
        table.stats-table td {
            border: 1px solid #d5d5db;
            padding: 6px 8px;
            text-align: center;
            font-size: 9.5px;
        }
        table.stats-table .stat-value {
            font-size: 13px;
            font-weight: bold;
            color: #1a1a2e;
            display: block;
        }
        table.stats-table .stat-label {
            color: #666666;
            font-size: 8.5px;
            text-transform: uppercase;
        }

        table.card-table {
            width: 100%;
            border-collapse: collapse;
        }
        table.card-table th {
            background-color: #f0f0f3;
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            color: #444444;
        }
        table.card-table td {
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            font-size: 9.5px;
            background-color: #ffffff;
            vertical-align: top;
        }
        table.card-table tr:nth-child(even) td {
            background-color: #fafafa;
        }
        .status-active { color: #0a7a3d; font-weight: bold; }
        .status-suspended { color: #a35b00; font-weight: bold; }
        .status-terminated { color: #b3261e; font-weight: bold; }

        .empty-note {
            font-size: 10px;
            color: #888888;
            font-style: italic;
            padding: 8px 0;
        }

        .signatures {
            width: 100%;
            margin-top: 36px;
            border-collapse: collapse;
        }
        .signatures td {
            width: 50%;
            text-align: center;
            font-size: 9px;
            color: #444444;
            padding-top: 28px;
        }
        .signature-line {
            border-top: 1px solid #888888;
            width: 80%;
            margin: 0 auto 4px auto;
        }
    </style>
</head>
<body>

    <div class="letterhead-bg"></div>

    <table class="header">
        <tr>
            <td>
                <div class="doc-title">Card Inventory</div>
                <div class="doc-subtitle">Issued ICCT cards — status &amp; balances</div>
            </td>
            <td class="meta">
                @if (!empty($scopeNote))
                    <div><strong>Filters:</strong> {{ $scopeNote }}</div>
                @endif
                <div><strong>Generated by:</strong> {{ $generatedBy }}</div>
                <div><strong>Generated on:</strong> {{ $generatedAt->format('M d, Y g:i A') }}</div>
            </td>
        </tr>
    </table>

    <table class="stats-table">
        <tr>
            <td style="width: 25%;">
                <span class="stat-value">{{ $stats['total'] }}</span>
                <span class="stat-label">Total cards</span>
            </td>
            <td style="width: 25%;">
                <span class="stat-value">{{ $stats['active'] }}</span>
                <span class="stat-label">Active</span>
            </td>
            <td style="width: 25%;">
                <span class="stat-value">{{ $stats['inactive'] }}</span>
                <span class="stat-label">Suspended / Terminated</span>
            </td>
            <td style="width: 25%;">
                <span class="stat-value">&#8369;{{ number_format($stats['balance'], 2) }}</span>
                <span class="stat-label">Total balance outstanding</span>
            </td>
        </tr>
    </table>

    @if ($cards->isEmpty())
        <p class="empty-note">No cards matched the selected filters.</p>
    @else
        <table class="card-table">
            <thead>
                <tr>
                    <th style="width: 18%;">Card No.</th>
                    <th style="width: 24%;">Cardholder</th>
                    <th style="width: 12%;">Role</th>
                    <th style="width: 14%;">Balance</th>
                    <th style="width: 14%;">Status</th>
                    <th style="width: 18%;">Issued</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($cards as $card)
                    <tr>
                        <td>{{ $card->card_number }}</td>
                        <td>{{ $card->user?->name ?? 'Unknown' }} ({{ $card->user?->user_code }})</td>
                        <td>{{ ucfirst($card->user?->role ?? '—') }}</td>
                        <td>&#8369;{{ number_format($card->balance, 2) }}</td>
                        <td><span class="status-{{ $card->status }}">{{ ucfirst($card->status) }}</span></td>
                        <td>{{ $card->created_at->format('Y-m-d') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <table class="signatures">
        <tr>
            <td>
                <div class="signature-line"></div>
                Prepared by
            </td>
            <td>
                <div class="signature-line"></div>
                Verified by
            </td>
        </tr>
    </table>

</body>
</html>
