<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dispatch Log</title>
    <style>
        @include('pdf.partials.letterhead-style')

        body {
            font-family: 'Helvetica', Arial, sans-serif;
            color: #1a1a1a;
            font-size: 10.5px;
            margin: 0;
            padding: 0;
        }

        .header {
            width: 100%;
            padding-bottom: 8px;
            margin-bottom: 6px;
            border-bottom: 1px solid #d5d5db;
        }
        .header td { vertical-align: top; }
        .doc-title {
            font-size: 14px;
            font-weight: bold;
            color: #1a1a2e;
        }
        .doc-subtitle {
            font-size: 9.5px;
            color: #666666;
            margin-top: 2px;
        }
        .meta {
            text-align: right;
            font-size: 9.5px;
            color: #444444;
        }
        .meta strong { color: #1a1a1a; }

        .route-title {
            background-color: #1a1a2e;
            color: #ffffff;
            font-size: 11.5px;
            font-weight: bold;
            padding: 5px 8px;
            margin-top: 14px;
            margin-bottom: 0;
        }

        .status-label {
            font-size: 10px;
            font-weight: bold;
            padding: 4px 2px;
            margin-top: 8px;
            margin-bottom: 0;
        }
        .status-label.departed { color: #0a7a3d; }
        .status-label.queued { color: #a35b00; }

        table.log-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 4px;
        }
        table.log-table th {
            background-color: #f0f0f3;
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            color: #444444;
        }
        table.log-table td {
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            font-size: 9.5px;
            background-color: #ffffff;
        }
        table.log-table tr:nth-child(even) td {
            background-color: #fafafa;
        }
        .empty-note {
            font-size: 10px;
            color: #888888;
            font-style: italic;
            padding: 8px 0;
        }

        .summary {
            margin-top: 16px;
            font-size: 9.5px;
            color: #444444;
            border-top: 1px solid #d5d5db;
            padding-top: 8px;
        }
        .signatures {
            width: 100%;
            margin-top: 36px;
            border-collapse: collapse;
        }
        .signatures td {
            width: 50%;
            text-align: center;
            font-size: 9px;
            color: #444444;
            padding-top: 28px;
        }
        .signature-line {
            border-top: 1px solid #888888;
            width: 80%;
            margin: 0 auto 4px auto;
        }
    </style>
</head>
<body>

    <div class="letterhead-bg"></div>

    <table class="header">
        <tr>
            <td>
                <div class="doc-title">{{ $title ?? 'Daily Dispatch Log' }}</div>
                <div class="doc-subtitle">{{ $subtitle ?? 'Vehicle queueing & departure record' }}</div>
            </td>
            <td class="meta">
                <div>
                    <strong>Period:</strong>
                    @if ($from && $to)
                        {{ $from->format('M d, Y') }}
                        @if (!$from->isSameDay($to))
                            &ndash; {{ $to->format('M d, Y') }}
                        @endif
                    @else
                        All time
                    @endif
                </div>
                @if (!empty($scopeNote))
                    <div><strong>Scope:</strong> {{ $scopeNote }}</div>
                @endif
                <div><strong>Generated by:</strong> {{ $generatedBy }}</div>
                <div><strong>Generated on:</strong> {{ $generatedAt->format('M d, Y g:i A') }}</div>
            </td>
        </tr>
    </table>

    @forelse ($grouped as $destination => $groups)
        <div class="route-title">{{ $destination }}</div>

        @if ($groups['departed']->isNotEmpty())
            <div class="status-label departed">Departed</div>
            <table class="log-table">
                <thead>
                    <tr>
                        <th style="width: 28%;">Operator Name</th>
                        <th style="width: 20%;">Plate #</th>
                        <th style="width: 20%;">Body #</th>
                        <th style="width: 32%;">Departure Time</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($groups['departed'] as $entry)
                        <tr>
                            <td>{{ $entry->user?->name ?? '—' }}</td>
                            <td>{{ $entry->plate_number }}</td>
                            <td>{{ $entry->vehicle?->body_number ?? '—' }}</td>
                            <td>{{ $entry->time_departed?->format('M d, g:i A') ?? '—' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif

        @if ($groups['queued']->isNotEmpty())
            <div class="status-label queued">Currently Queued</div>
            <table class="log-table">
                <thead>
                    <tr>
                        <th style="width: 28%;">Operator Name</th>
                        <th style="width: 20%;">Plate #</th>
                        <th style="width: 20%;">Body #</th>
                        <th style="width: 32%;">Departure Time</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($groups['queued'] as $entry)
                        <tr>
                            <td>{{ $entry->user?->name ?? '—' }}</td>
                            <td>{{ $entry->plate_number }}</td>
                            <td>{{ $entry->vehicle?->body_number ?? '—' }}</td>
                            <td>—</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    @empty
        <p class="empty-note">No vehicles were logged for the selected period.</p>
    @endforelse

    <div class="summary">
        <strong>Total vehicles logged:</strong> {{ $totalCount }}
    </div>

    <table class="signatures">
        <tr>
            <td>
                <div class="signature-line"></div>
                Prepared by
            </td>
            <td>
                <div class="signature-line"></div>
                Verified by
            </td>
        </tr>
    </table>

</body>
</html>