<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>My Fleet</title>
    <style>
        @include('pdf.partials.letterhead-style')

        body {
            font-family: 'Helvetica', Arial, sans-serif;
            color: #1a1a1a;
            font-size: 10.5px;
            margin: 0;
            padding: 0;
        }

        .header {
            width: 100%;
            padding-bottom: 8px;
            margin-bottom: 10px;
            border-bottom: 1px solid #d5d5db;
        }
        .header td { vertical-align: top; }
        .doc-title {
            font-size: 14px;
            font-weight: bold;
            color: #1a1a2e;
        }
        .doc-subtitle {
            font-size: 9.5px;
            color: #666666;
            margin-top: 2px;
        }
        .meta {
            text-align: right;
            font-size: 9.5px;
            color: #444444;
        }
        .meta strong { color: #1a1a1a; }

        table.fleet-table {
            width: 100%;
            border-collapse: collapse;
        }
        table.fleet-table th {
            background-color: #f0f0f3;
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            color: #444444;
        }
        table.fleet-table td {
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            font-size: 9.5px;
            background-color: #ffffff;
            vertical-align: top;
        }
        table.fleet-table tr:nth-child(even) td {
            background-color: #fafafa;
        }
        .status-valid { color: #0a7a3d; font-weight: bold; }
        .status-expiring { color: #a35b00; font-weight: bold; }
        .status-expired { color: #b3261e; font-weight: bold; }
        .status-none { color: #888888; font-style: italic; }

        .empty-note {
            font-size: 10px;
            color: #888888;
            font-style: italic;
            padding: 8px 0;
        }

        .signatures {
            width: 100%;
            margin-top: 36px;
            border-collapse: collapse;
        }
        .signatures td {
            width: 50%;
            text-align: center;
            font-size: 9px;
            color: #444444;
            padding-top: 28px;
        }
        .signature-line {
            border-top: 1px solid #888888;
            width: 80%;
            margin: 0 auto 4px auto;
        }
    </style>
</head>
<body>

    <div class="letterhead-bg"></div>

    <table class="header">
        <tr>
            <td>
                <div class="doc-title">My Fleet</div>
                <div class="doc-subtitle">Vehicle roster &amp; compliance document status</div>
            </td>
            <td class="meta">
                <div><strong>Operator:</strong> {{ $operator->name }} ({{ $operator->user_code }})</div>
                <div><strong>Generated by:</strong> {{ $generatedBy }}</div>
                <div><strong>Generated on:</strong> {{ $generatedAt->format('M d, Y g:i A') }}</div>
            </td>
        </tr>
    </table>

    @if ($vehicles->isEmpty())
        <p class="empty-note">No vehicles are registered under this account.</p>
    @else
        <table class="fleet-table">
            <thead>
                <tr>
                    <th style="width: 11%;">Plate No.</th>
                    <th style="width: 10%;">Type</th>
                    <th style="width: 13%;">Route</th>
                    <th style="width: 12%;">Engine No.</th>
                    <th style="width: 12%;">Body No.</th>
                    <th style="width: 12%;">Chassis No.</th>
                    <th style="width: 14%;">Validity Date of Franchise</th>
                    <th style="width: 10%;">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($vehicles as $vehicle)
                    @php
                        $status = $vehicle->documentStatus();
                        $statusLabel = match ($status) {
                            'expired'  => 'Expired',
                            'expiring' => 'Expiring Soon',
                            'valid'    => 'Valid',
                            default    => 'No documents on file',
                        };
                        $statusClass = match ($status) {
                            'expired'  => 'status-expired',
                            'expiring' => 'status-expiring',
                            'valid'    => 'status-valid',
                            default    => 'status-none',
                        };
                    @endphp
                    <tr>
                        <td>{{ $vehicle->plate_number }}</td>
                        <td>{{ $vehicle->vehicle_type }}</td>
                        <td>{{ $vehicle->route_list?->terminal ?? '—' }}</td>
                        <td>{{ $vehicle->engine_number ?? '—' }}</td>
                        <td>{{ $vehicle->body_number ?? '—' }}</td>
                        <td>{{ $vehicle->chassis_number ?? '—' }}</td>
                        <td>{{ $vehicle->franchise_expiry_date?->format('Y-m-d') ?? '—' }}</td>
                        <td><span class="{{ $statusClass }}">{{ $statusLabel }}</span></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <table class="signatures">
        <tr>
            <td>
                <div class="signature-line"></div>
                Operator signature
            </td>
            <td>
                <div class="signature-line"></div>
                Verified by (terminal admin)
            </td>
        </tr>
    </table>

</body>
</html>
