<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Routes &amp; Fares</title>
    <style>
        @include('pdf.partials.letterhead-style')

        body {
            font-family: 'Helvetica', Arial, sans-serif;
            color: #1a1a1a;
            font-size: 10.5px;
            margin: 0;
            padding: 0;
        }

        .header {
            width: 100%;
            padding-bottom: 8px;
            margin-bottom: 18px;
            border-bottom: 1px solid #d5d5db;
        }
        .header td { vertical-align: top; }
        .doc-title {
            font-size: 14px;
            font-weight: bold;
            color: #1a1a2e;
        }
        .doc-subtitle {
            font-size: 9.5px;
            color: #666666;
            margin-top: 2px;
        }
        .meta {
            text-align: right;
            font-size: 9.5px;
            color: #444444;
        }
        .meta strong { color: #1a1a1a; }

        table.fare-table {
            width: 100%;
            border-collapse: collapse;
        }
        table.fare-table th {
            background-color: #a9c4e0;
            border: 1px solid #6b6b6b;
            padding: 8px 10px;
            text-align: center;
            font-size: 11px;
            font-weight: bold;
            color: #1a1a1a;
        }
        table.fare-table td {
            border: 1px solid #6b6b6b;
            padding: 7px 10px;
            font-size: 10.5px;
            vertical-align: middle;
        }
        .vehicle-type-cell {
            font-weight: bold;
            font-size: 11px;
            background-color: #fafafa;
        }
        .route-cell {
            font-weight: bold;
        }
        .fare-cell, .operators-cell {
            text-align: center;
        }
        .no-routes {
            font-style: italic;
            color: #888888;
            text-align: center;
        }

        .signature-block {
            margin-top: 60px;
        }
        .signature-line {
            border-top: 1px solid #444444;
            width: 220px;
            margin-bottom: 2px;
        }
        .signature-name {
            font-weight: bold;
            font-size: 10.5px;
        }
        .signature-role {
            font-size: 9.5px;
            color: #444444;
        }
    </style>
</head>
<body>

    <div class="letterhead-bg"></div>

    <table class="header">
        <tr>
            <td>
                <div class="doc-title">Routes &amp; Fare Matrix</div>
                <div class="doc-subtitle">Official routes, fares, and operator counts</div>
            </td>
            <td class="meta">
                <div><strong>Generated by:</strong> {{ $generatedBy }}</div>
                <div><strong>Generated on:</strong> {{ $generatedAt->format('M d, Y g:i A') }}</div>
            </td>
        </tr>
    </table>

    <table class="fare-table">
        <thead>
            <tr>
                <th style="width: 16%;">&nbsp;</th>
                <th style="width: 40%;">ROUTES</th>
                <th style="width: 22%;">FARE</th>
                <th style="width: 22%;">NO. of Operators</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($vehicleTypes as $type)
                @php $routeCount = $type->routeList->count(); @endphp

                @if ($routeCount === 0)
                    <tr>
                        <td class="vehicle-type-cell">{{ $type->vehicle_type }}</td>
                        <td colspan="3" class="no-routes">No routes configured</td>
                    </tr>
                @else
                    @foreach ($type->routeList as $index => $route)
                        <tr>
                            @if ($index === 0)
                                <td class="vehicle-type-cell" rowspan="{{ $routeCount }}">{{ $type->vehicle_type }}</td>
                            @endif
                            <td class="route-cell">{{ $route->terminal }}</td>
                            <td class="fare-cell">{{ number_format($route->fare, 0) }}</td>
                            <td class="operators-cell">{{ $route->vehicles_count }}</td>
                        </tr>
                    @endforeach
                @endif
            @endforeach
        </tbody>
    </table>

    <div class="signature-block">
        <div class="signature-line"></div>
        <div class="signature-name">{{ $generatedBy }}</div>
        <div class="signature-role">Prepared by</div>
    </div>

</body>
</html>
