<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Transactions Report</title>
    <style>
        @include('pdf.partials.letterhead-style')

        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: #1a1a1a;
            font-size: 10.5px;
            margin: 0;
            padding: 0;
        }

        .header {
            width: 100%;
            padding-bottom: 8px;
            margin-bottom: 6px;
            border-bottom: 1px solid #d5d5db;
        }
        .header td { vertical-align: top; }
        .doc-title {
            font-size: 14px;
            font-weight: bold;
            color: #1a1a2e;
        }
        .doc-subtitle {
            font-size: 9.5px;
            color: #666666;
            margin-top: 2px;
        }
        .meta {
            text-align: right;
            font-size: 9.5px;
            color: #444444;
        }
        .meta strong { color: #1a1a1a; }

        .section-title {
            background-color: #1a1a2e;
            color: #ffffff;
            font-size: 11.5px;
            font-weight: bold;
            padding: 5px 8px;
            margin-top: 14px;
            margin-bottom: 0;
        }

        table.log-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 4px;
        }
        table.log-table th {
            background-color: #f0f0f3;
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            color: #444444;
        }
        table.log-table td {
            border: 1px solid #d5d5db;
            padding: 5px 6px;
            font-size: 9.5px;
            background-color: #ffffff;
        }
        table.log-table tr:nth-child(even) td {
            background-color: #fafafa;
        }
        table.log-table td.amount, table.log-table th.amount {
            text-align: right;
        }
        .subtotal-row td {
            font-weight: bold;
            background-color: #f0f0f3 !important;
        }
        .empty-note {
            font-size: 10px;
            color: #888888;
            font-style: italic;
            padding: 8px 0;
        }

        .summary {
            margin-top: 18px;
            border-top: 1px solid #d5d5db;
            padding-top: 8px;
        }
        table.summary-table {
            width: 60%;
            margin-left: auto;
            border-collapse: collapse;
            font-size: 10px;
        }
        table.summary-table td {
            padding: 3px 6px;
        }
        table.summary-table td.label { color: #444444; }
        table.summary-table td.value { text-align: right; }
        table.summary-table tr.grand-total td {
            border-top: 1px solid #1a1a1a;
            font-weight: bold;
            font-size: 11.5px;
            padding-top: 6px;
        }
        table.summary-table tr.section-heading td {
            font-weight: bold;
            padding-top: 8px;
            color: #1a1a2e;
        }

        .note {
            margin-top: 10px;
            font-size: 9px;
            color: #666666;
            font-style: italic;
        }

        .signatures {
            width: 100%;
            margin-top: 36px;
            border-collapse: collapse;
        }
        .signatures td {
            width: 50%;
            text-align: center;
            font-size: 9px;
            color: #444444;
            padding-top: 28px;
        }
        .signature-line {
            border-top: 1px solid #888888;
            width: 80%;
            margin: 0 auto 4px auto;
        }
    </style>
</head>
<body>

    <div class="letterhead-bg"></div>

    <table class="header">
        <tr>
            <td>
                <div class="doc-title">Transactions Report</div>
                <div class="doc-subtitle">
                    @php
                        $filterLabels = array_filter([
                            $category ? ($categoryLabels[$category] ?? ucfirst($category)) : null,
                            $mode ? ($modeLabels[$mode] ?? ucfirst($mode)) . ' payments' : null,
                            $status ? ucfirst($status) . ' only' : null,
                        ]);
                    @endphp
                    {{ $filterLabels ? implode(' · ', $filterLabels) : 'All top-ups, queue fees, fare payments & card issuance' }}
                </div>
            </td>
            <td class="meta">
                <div>
                    <strong>Date:</strong>
                    @if ($from && $to)
                        {{ $from->format('M d, Y') }}
                        @if (!$from->isSameDay($to))
                            &ndash; {{ $to->format('M d, Y') }}
                        @endif
                    @else
                        All time
                    @endif
                </div>
                <div><strong>Generated by:</strong> {{ $generatedBy }}</div>
                <div><strong>Generated on:</strong> {{ $generatedAt->format('M d, Y g:i A') }}</div>
            </td>
        </tr>
    </table>

    @forelse ($grouped as $categoryKey => $categoryRows)
        <div class="section-title">{{ $categoryLabels[$categoryKey] ?? ucfirst($categoryKey) }}</div>
        @include('pdf.partials.transaction-table', ['rows' => $categoryRows])
    @empty
        <p class="empty-note">No transactions matched the selected filters.</p>
    @endforelse

    {{-- ===================== SUMMARY ===================== --}}
    <div class="summary">
        <table class="summary-table">
            <tr class="section-heading"><td colspan="2">By category</td></tr>
            @foreach ($categoryLabels as $key => $label)
                @if (isset($totalsByCategory[$key]))
                    <tr>
                        <td class="label">{{ $label }} ({{ $grouped[$key]->count() ?? 0 }})</td>
                        <td class="value">&#8369;{{ number_format($totalsByCategory[$key], 2) }}</td>
                    </tr>
                @endif
            @endforeach

            <tr class="section-heading"><td colspan="2">By payment type</td></tr>
            @foreach ($modeLabels as $key => $label)
                @if (isset($totalsByMode[$key]) && $key !== 'n/a')
                    <tr>
                        <td class="label">{{ $label }}</td>
                        <td class="value">&#8369;{{ number_format($totalsByMode[$key], 2) }}</td>
                    </tr>
                @endif
            @endforeach

            <tr class="grand-total">
                <td class="label">Total revenue</td>
                <td class="value">&#8369;{{ number_format($grandTotal, 2) }}</td>
            </tr>
        </table>

        <p class="note">
            Fare payments are credited to the operator's card as withdrawable points regardless of whether the rider paid in cash or by tapping their card — they are not retained by the terminal the way queue fees are.
        </p>
    </div>

    <table class="signatures">
        <tr>
            <td>
                <div class="signature-line"></div>
                Prepared by
            </td>
            <td>
                <div class="signature-line"></div>
                Verified by
            </td>
        </tr>
    </table>

</body>
</html>