<?php

use Livewire\Component;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Computed;
use Livewire\WithPagination;

use App\Models\User;
use App\Models\Card;
use App\Models\CardReport;
use App\Models\Notification;
use App\Models\UserNotification;
use App\Events\NotificationEvent;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

new #[Layout('layouts.admin-layout')] class extends Component
{
    use WithPagination;

    public $search;
    public string $reportFilter = 'pending';

    // For the report detail modal
    public ?int $selectedReportId = null;
    public string $rejectionReason = '';

    // NEW: store the new card UID entered in the modal
    public ?string $newCardUid = null;

    #[Computed]
    public function getUsers() {
        return User::with('card')
            ->whereIn('role', ['operator', 'commuter'])
            ->whereHas('card')
            ->when($this->search, function ($query) {
                $query->where(function ($q) {
                    $q->where('name', 'like', '%' . $this->search . '%')
                      ->orWhere('user_code', 'like', '%' . $this->search . '%')
                      ->orWhereHas('card', fn($q) =>
                          $q->where('card_number', 'like', '%' . $this->search . '%')
                      );
                });
            })
            ->paginate(10);
    }

    #[Computed]
    public function cardStats() {
        $cards = Card::whereHas('user', fn($q) => $q->whereIn('role', ['operator', 'commuter']));
        return [
            'total'    => $cards->count(),
            'active'   => (clone $cards)->where('status', 'active')->count(),
            'inactive' => (clone $cards)->where('status', '!=', 'active')->count(),
        ];
    }

    #[Computed]
    public function cardReports() {
        return CardReport::with(['user', 'card', 'approvedBy'])
            ->when($this->reportFilter !== 'all', fn($q) => $q->where('status', $this->reportFilter))
            ->latest()
            ->get();
    }

    #[Computed]
    public function pendingReportCount() {
        return CardReport::where('status', 'pending')->count();
    }

    #[Computed]
    public function selectedReport() {
        if (!$this->selectedReportId) return null;
        return CardReport::with(['user', 'card', 'approvedBy', 'newCard'])->find($this->selectedReportId);
    }

    public function viewReport(int $reportId): void
    {
        $this->selectedReportId = $reportId;
        $this->rejectionReason = '';
        $this->newCardUid = '';
        $this->dispatch('open-report-modal');
    }

    public function approveReport(): void
    {
        $report = CardReport::with(['card', 'user'])->findOrFail($this->selectedReportId);

        if ($report->status !== 'pending') {
            Flux::toast(variant: 'warning', heading: 'Already processed.', text: 'This report has already been handled.');
            return;
        }

        if (empty($this->newCardUid)) {
            Flux::toast(
                variant: 'danger',
                heading: 'New card UID required.',
                text: 'Please enter the UID of the new blank card.'
            );
            return;
        }

        // Ensure the UID is not already used
        if (Card::where('uid', $this->newCardUid)->exists()) {
            Flux::toast(
                variant: 'danger',
                heading: 'Duplicate UID.',
                text: 'A card with that UID already exists in the system.'
            );
            return;
        }

        // Declare variable outside transaction so we can use it after
        $newCard = null;

        DB::transaction(function () use ($report, &$newCard) {
            $oldCard = $report->card;

            // Create the new card for the same user
            $newCard = Card::create([
                'user_id'     => $oldCard->user_id,
                'uid'         => $this->newCardUid,
                'balance'     => $oldCard->balance,
                'status'      => 'active',
                // card_number auto-generated by boot()
            ]);

            // Suspend the old card
            $oldCard->update(['status' => 'suspended']);

            // Close the report
            $report->update([
                'status'      => 'approved',
                'approved_by' => auth()->id(),
                'new_card_id' => $newCard->id,
                'approved_at' => now(),
            ]);
        });

        // Notify the commuter
        $notification = Notification::create([
            'type'    => 'Card',
            'title'   => 'Replacement Card Issued',
            'message' => 'Your lost card report has been approved. Your new card is now active and your balance has been transferred. Please collect your new card at the terminal.',
            'metadata' => [
                'report_id'   => $report->id,
                'new_card_id' => $newCard->id,
            ],
        ]);

        UserNotification::create([
            'notification_id' => $notification->id,
            'user_id'         => $report->user_id,
        ]);

        broadcast(new NotificationEvent());

        $this->selectedReportId = null;
        $this->dispatch('close-report-modal');

        Flux::toast(
            variant: 'success',
            heading: 'Replacement issued.',
            text: 'Old card suspended. New card created with balance transferred.',
        );
    }

    public function rejectReport(): void
    {
        $this->validate(['rejectionReason' => 'required|string|min:5|max:500'], [
            'rejectionReason.required' => 'Please provide a reason for rejection.',
            'rejectionReason.min'      => 'Reason must be at least 5 characters.',
        ]);

        $report = CardReport::findOrFail($this->selectedReportId);

        if ($report->status !== 'pending') {
            Flux::toast(variant: 'warning', heading: 'Already processed.');
            return;
        }

        $report->update([
            'status'           => 'rejected',
            'approved_by'      => auth()->id(),
            'rejection_reason' => $this->rejectionReason,
            'approved_at'      => now(),
        ]);

        // Notify the commuter
        $notification = Notification::create([
            'type'    => 'Card',
            'title'   => 'Lost Card Report Rejected',
            'message' => 'Your lost card report has been rejected. Reason: ' . $this->rejectionReason . '. Please visit the terminal or contact support if you have questions.',
            'metadata' => [
                'report_id'        => $report->id,
                'rejection_reason' => $this->rejectionReason,
            ],
        ]);

        UserNotification::create([
            'notification_id' => $notification->id,
            'user_id'         => $report->user_id,
        ]);

        broadcast(new NotificationEvent());

        $this->selectedReportId = null;
        $this->rejectionReason = '';
        $this->dispatch('close-report-modal');

        Flux::toast(variant: 'success', heading: 'Report rejected.', text: 'The commuter has been notified.');
    }

    public function updatedSearch(): void
    {
        $this->resetPage();
    }
};

?>

<div>
    {{-- Heading --}}
    <div class="flex items-start justify-between gap-4 mb-6">
        <div>
            <x-heading
                size="xl"
                class="!font-primary !font-bold !text-light-txt-primary dark:!text-dark-txt-primary"
                style="font-size: var(--text-page-title)"
            >
                Cards
            </x-heading>
            <x-text variant="subtle" class="!font-secondary mt-1 block" style="font-size: var(--text-helper)">
                View all registered cards and manage lost card reports.
            </x-text>
        </div>
    </div>

    {{-- Stats --}}
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-2 sm:gap-3 mb-6">
        <flux:card class="p-3 sm:p-4">
            <div class="flex items-center gap-1.5 sm:gap-2 mb-1.5">
                <div class="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7 rounded-lg bg-primary/10 dark:bg-primary/20 shrink-0">
                    <flux:icon.credit-card class="w-3.5 h-3.5 sm:w-4 sm:h-4 text-primary dark:text-dark-txt-primary" />
                </div>
                <x-text class="font-secondary text-xs sm:text-stat-label text-light-txt-muted dark:text-dark-txt-muted">
                    Total cards
                </x-text>
            </div>
            <x-text class="font-primary text-stat-value font-bold text-light-txt-primary dark:text-dark-txt-primary block">
                {{ $this->cardStats['total'] }}
            </x-text>
        </flux:card>

        <flux:card class="p-3 sm:p-4">
            <div class="flex items-center gap-1.5 sm:gap-2 mb-1.5">
                <div class="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7 rounded-lg bg-success/10 dark:bg-dark-success/20 shrink-0">
                    <flux:icon.check-circle class="w-3.5 h-3.5 sm:w-4 sm:h-4 text-success dark:text-dark-success" />
                </div>
                <x-text class="font-secondary text-xs sm:text-stat-label text-light-txt-muted dark:text-dark-txt-muted">
                    Active
                </x-text>
            </div>
            <x-text class="font-primary text-stat-value font-bold text-success dark:text-dark-success block">
                {{ $this->cardStats['active'] }}
            </x-text>
        </flux:card>

        <flux:card class="p-3 sm:p-4">
            <div class="flex items-center gap-1.5 sm:gap-2 mb-1.5">
                <div class="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7 rounded-lg bg-danger/10 dark:bg-dark-danger/20 shrink-0">
                    <flux:icon.exclamation-triangle class="w-3.5 h-3.5 sm:w-4 sm:h-4 text-danger dark:text-dark-danger" />
                </div>
                <x-text class="font-secondary text-xs sm:text-stat-label text-light-txt-muted dark:text-dark-txt-muted">
                    Inactive / suspended
                </x-text>
            </div>
            <x-text class="font-primary text-stat-value font-bold text-danger dark:text-dark-danger block">
                {{ $this->cardStats['inactive'] }}
            </x-text>
        </flux:card>
    </div>

    {{-- Search --}}
    <div class="flex items-center gap-3 mb-4">
        <flux:input
            class="max-w-xs"
            size="sm"
            icon="magnifying-glass"
            placeholder="Search name, ID, card…"
            wire:model.live.debounce.300ms="search"
        />
    </div>

    {{-- Cards Table --}}
    <flux:card class="overflow-hidden p-0">
        <flux:table container:class="max-h-160">
            <flux:table.columns sticky class="bg-white dark:bg-zinc-900">
                <flux:table.column align="center" class="px-1! sm:px-2! md:px-4! py-2">#</flux:table.column>
                <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Owner ID</flux:table.column>
                <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Card no.</flux:table.column>
                <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Name</flux:table.column>
                <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Balance</flux:table.column>
                <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Status</flux:table.column>
                <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Registered</flux:table.column>
                <flux:table.column align="center" class="px-1! sm:px-2! md:px-4! py-2">Actions</flux:table.column>
            </flux:table.columns>

            <flux:table.rows>
                @forelse ($this->getUsers as $index => $user)
                    <flux:table.row :key="$user->id">
                        <flux:table.cell align="center" class="px-1! sm:px-2! md:px-4! py-1.5 md:py-2 font-secondary text-xs md:text-table-row text-light-txt-muted dark:text-dark-txt-muted">
                            {{ ($this->getUsers->currentPage() - 1) * $this->getUsers->perPage() + $index + 1 }}
                        </flux:table.cell>

                        <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2 font-secondary text-xs md:text-table-row text-light-txt-muted dark:text-dark-txt-muted">
                            {{ $user->user_code }}
                        </flux:table.cell>

                        <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                            <span class="font-mono text-xs md:text-table-row tracking-widest text-light-txt-muted dark:text-dark-txt-muted">
                                **** **** **** {{ substr($user->card->card_number, -4) }}
                            </span>
                        </flux:table.cell>

                        <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                            <div class="flex items-center justify-center gap-2">
                                <flux:avatar size="xs" src="{{ $user->avatar_url }}" name="{{ $user->name }}" />
                                <span class="font-secondary text-xs md:text-table-row text-light-txt-body dark:text-dark-txt-body">{{ $user->name }}</span>
                            </div>
                        </flux:table.cell>

                        <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2 font-secondary text-xs md:text-table-row tabular-nums font-medium text-light-txt-primary dark:text-dark-txt-primary">
                            {{ number_format($user->card->balance, 2) }}
                        </flux:table.cell>

                        <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                            @if ($user->card->status === 'active')
                                <flux:badge color="green" size="sm">Active</flux:badge>
                            @else
                                <flux:badge color="red" size="sm">{{ ucfirst($user->card->status) }}</flux:badge>
                            @endif
                        </flux:table.cell>

                        <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2 font-secondary text-xs md:text-table-row text-light-txt-muted dark:text-dark-txt-muted tabular-nums">
                            {{ $user->card->created_at->format('Y-m-d') }}
                        </flux:table.cell>

                        <flux:table.cell align="center" class="px-1! sm:px-2! md:px-4! py-1.5 md:py-2">
                            <flux:link href="/admin/card/transaction/{{ $user->id }}" wire:navigate>
                                <flux:button variant="ghost" size="sm" icon="ellipsis-horizontal" inset="top bottom" />
                            </flux:link>
                        </flux:table.cell>
                    </flux:table.row>
                @empty
                    <flux:table.row>
                        <flux:table.cell colspan="8">
                            <div class="flex flex-col items-center justify-center py-12 gap-2">
                                <flux:icon.credit-card class="w-8 h-8 text-zinc-300" />
                                <p class="text-sm text-zinc-400">No cards found.</p>
                                @if ($search)
                                    <p class="text-xs text-zinc-400">Try a different search term.</p>
                                @endif
                            </div>
                        </flux:table.cell>
                    </flux:table.row>
                @endforelse
            </flux:table.rows>
        </flux:table>
    </flux:card>

    {{-- Pagination --}}
    <div class="mt-4">
        {{ $this->getUsers->links() }}
    </div>

    <div class="mt-10">
        <div class="flex items-center justify-between mb-4">
            <div class="flex items-center gap-2">
                <flux:heading size="lg" class="!font-primary !font-bold !text-light-txt-primary dark:!text-dark-txt-primary">
                    Card Reports
                </flux:heading>
                @if ($this->pendingReportCount > 0)
                    <flux:badge color="red" size="sm">{{ $this->pendingReportCount }} pending</flux:badge>
                @endif
            </div>
            <flux:select wire:model.live="reportFilter" size="sm" class="w-40">
                <flux:select.option value="pending">Pending</flux:select.option>
                <flux:select.option value="approved">Approved</flux:select.option>
                <flux:select.option value="rejected">Rejected</flux:select.option>
                <flux:select.option value="all">All</flux:select.option>
            </flux:select>
        </div>

        {{-- Reports Table --}}
        <flux:card class="overflow-hidden p-0">
            <flux:table>
                <flux:table.columns sticky class="bg-white dark:bg-zinc-900">
                    <flux:table.column align="center" class="px-1! sm:px-2! md:px-4! py-2">#</flux:table.column>
                    <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Commuter</flux:table.column>
                    <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Reason</flux:table.column>
                    <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Submitted</flux:table.column>
                    <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Status</flux:table.column>
                    <flux:table.column align="center" class="px-1! sm:px-2! md:px-4! py-2">Actions</flux:table.column>
                </flux:table.columns>

                <flux:table.rows>
                    @forelse ($this->cardReports as $index => $report)
                        <flux:table.row :key="$report->id">
                            <flux:table.cell align="center" class="px-1! sm:px-2! md:px-4! py-1.5 md:py-2 font-secondary text-xs md:text-table-row text-light-txt-muted dark:text-dark-txt-muted">
                                {{ $index + 1 }}
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                                <div class="flex items-center justify-center gap-2">
                                    <flux:avatar size="xs" src="{{ $report->user->avatar_url }}" name="{{ $report->user->name }}" />
                                    <div class="text-left">
                                        <p class="font-secondary text-xs md:text-table-row font-medium text-light-txt-primary dark:text-dark-txt-primary">{{ $report->user->name }}</p>
                                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted">{{ $report->user->user_code }}</p>
                                    </div>
                                </div>
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                                <flux:badge size="sm" color="{{ match($report->reason) { 'lost' => 'red', 'damaged' => 'yellow', default => 'zinc' } }}">
                                    {{ ucfirst($report->reason) }}
                                </flux:badge>
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2 font-secondary text-xs md:text-table-row text-light-txt-muted dark:text-dark-txt-muted tabular-nums">
                                {{ $report->created_at->format('M d, Y') }}
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                                @if ($report->status === 'pending')
                                    <flux:badge color="yellow" size="sm" icon="clock">Pending</flux:badge>
                                @elseif ($report->status === 'approved')
                                    <flux:badge color="green" size="sm" icon="check-circle">Approved</flux:badge>
                                @else
                                    <flux:badge color="red" size="sm" icon="x-circle">Rejected</flux:badge>
                                @endif
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1! sm:px-2! md:px-4! py-1.5 md:py-2">
                                <flux:button
                                    wire:click="viewReport({{ $report->id }})"
                                    variant="ghost"
                                    size="sm"
                                    icon="ellipsis-horizontal"
                                    inset="top bottom"
                                />
                            </flux:table.cell>
                        </flux:table.row>
                    @empty
                        <flux:table.row>
                            <flux:table.cell colspan="6">
                                <div class="flex flex-col items-center justify-center py-12 gap-2">
                                    <flux:icon.document-text class="w-8 h-8 text-zinc-300" />
                                    <p class="text-sm text-zinc-400">
                                        No {{ $reportFilter === 'all' ? '' : $reportFilter }} reports found.
                                    </p>
                                </div>
                            </flux:table.cell>
                        </flux:table.row>
                    @endforelse
                </flux:table.rows>
            </flux:table>
        </flux:card>
    </div>

    {{-- ─── Report Detail Modal ─────────────────────────────────────────────── --}}
    <flux:modal
        name="report-detail-modal"
        :closable="false"
        class="w-full max-w-[95vw] sm:max-w-lg md:max-w-2xl mx-auto max-h-[80vh] sm:max-h-[90vh] overflow-hidden rounded-xl"
        x-on:open-report-modal.window="$flux.modal('report-detail-modal').show()"
        x-on:close-report-modal.window="$flux.modal('report-detail-modal').close()"
    >
        @if ($this->selectedReport)
            @php $report = $this->selectedReport; @endphp
            <div class="flex flex-col max-h-[calc(80vh-2rem)] sm:max-h-[calc(90vh-2rem)] overflow-y-auto overscroll-contain p-4 sm:p-6 !pr-4 sm:!pr-6 space-y-5">

                {{-- Header --}}
                <div class="flex items-start justify-between">
                    <div>
                        <flux:heading size="xl" class="!font-primary !font-bold text-light-txt-primary dark:text-dark-txt-primary">
                            Lost Card Report
                        </flux:heading>
                        <flux:text class="mt-1 font-secondary text-sm text-light-txt-muted dark:text-dark-txt-muted">
                            Submitted {{ $report->created_at->format('M d, Y · h:i A') }}
                        </flux:text>
                    </div>

                    <flux:modal.close>
                        <button type="button" class="p-1 rounded-full hover:bg-light-subtle dark:hover:bg-dark-subtle text-light-txt-muted dark:text-dark-txt-muted -mt-1">
                            <flux:icon name="x-mark" class="w-5 h-5" />
                        </button>
                    </flux:modal.close>
                </div>

                {{-- Commuter info --}}
                <div class="flex items-center gap-3 p-3 rounded-lg bg-zinc-50 dark:bg-zinc-800">
                    <flux:avatar src="{{ $report->user->avatar_url }}" name="{{ $report->user->name }}" />
                    <div>
                        <p class="font-secondary text-sm font-medium text-light-txt-primary dark:text-dark-txt-primary">{{ $report->user->name }}</p>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted">{{ $report->user->user_code }}</p>
                    </div>
                    <div class="ml-auto text-right">
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted">Card no.</p>
                        <p class="font-mono text-xs tracking-widest text-light-txt-primary dark:text-dark-txt-primary">**** {{ substr($report->card->card_number, -4) }}</p>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mt-0.5">Balance: <span class="font-medium text-light-txt-primary dark:text-dark-txt-primary">₱{{ number_format($report->card->balance, 2) }}</span></p>
                    </div>
                </div>

                {{-- Reason & status --}}
                <div class="grid grid-cols-2 gap-4">
                    <div>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mb-1">Reason</p>
                        <flux:badge size="sm" color="{{ match($report->reason) { 'lost' => 'red', 'damaged' => 'yellow', default => 'zinc' } }}">
                            {{ ucfirst($report->reason) }}
                        </flux:badge>
                    </div>
                    <div>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mb-1">Status</p>
                        @if ($report->status === 'pending')
                            <flux:badge color="yellow" size="sm">Pending</flux:badge>
                        @elseif ($report->status === 'approved')
                            <flux:badge color="green" size="sm">Approved</flux:badge>
                        @else
                            <flux:badge color="red" size="sm">Rejected</flux:badge>
                        @endif
                    </div>
                </div>

                {{-- Description --}}
                <div>
                    <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mb-1">Description</p>
                    <p class="font-secondary text-sm text-light-txt-body dark:text-dark-txt-body bg-zinc-50 dark:bg-zinc-800 rounded-lg p-3">
                        {{ $report->description }}
                    </p>
                </div>

                {{-- Valid ID photo --}}
                @if ($report->valid_id_path)
                    <div>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mb-2">Valid ID submitted</p>
                        <img
                            src="{{ Storage::url($report->valid_id_path) }}"
                            alt="Valid ID"
                            class="w-full rounded-lg border border-zinc-200 dark:border-zinc-700 object-cover max-h-52"
                        />
                    </div>
                @endif

                {{-- Approved info --}}
                @if ($report->status === 'approved')
                    <div class="rounded-lg border border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/20 p-3 text-sm text-green-700 dark:text-green-400">
                        Approved by <strong>{{ $report->approvedBy?->name ?? 'Admin' }}</strong>
                        on {{ $report->approved_at?->format('M d, Y') }}.
                        New card: <span class="font-mono">**** {{ substr($report->newCard?->card_number, -4) }}</span>
                    </div>
                @endif

                {{-- Rejection info --}}
                @if ($report->status === 'rejected')
                    <div class="rounded-lg border border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/20 p-3 text-sm text-red-700 dark:text-red-400">
                        <p class="font-medium mb-1">Rejection reason:</p>
                        <p>{{ $report->rejection_reason }}</p>
                    </div>
                @endif

                {{-- NEW: New Card UID + Rejection reason (only when pending) --}}
                @if ($report->status === 'pending')
                    {{-- New Card UID field --}}
                    <div>
                        <flux:input
                            wire:model="newCardUid"
                            label="New Card UID"
                            placeholder="Enter the UID of the blank card"
                            class="font-mono"
                        />
                        <flux:error name="newCardUid" />
                        <p class="mt-1 text-xs text-light-txt-muted dark:text-dark-txt-muted">
                            This UID will be used to create a new card for the commuter.
                        </p>
                    </div>

                    {{-- Rejection reason --}}
                    <div>
                        <flux:textarea
                            wire:model="rejectionReason"
                            label="Rejection reason (required to reject)"
                            placeholder="Explain why the report is being rejected…"
                            rows="2"
                        />
                        <flux:error name="rejectionReason" />
                    </div>
                @endif

                {{-- Action buttons --}}
                <div class="flex flex-col-reverse sm:flex-row justify-end items-stretch sm:items-center gap-2 pt-2 border-t border-light-bd-default dark:border-dark-bd-default">
                    <flux:modal.close class="w-full sm:w-auto">
                        <flux:button variant="ghost" class="w-full sm:w-auto justify-center !font-secondary">
                            Close
                        </flux:button>
                    </flux:modal.close>

                    @if ($report->status === 'pending')
                        <flux:button
                            variant="danger"
                            wire:click="rejectReport"
                            wire:loading.attr="disabled"
                            wire:target="rejectReport"
                            wire:confirm="Reject this report? The commuter will need to re-submit."
                            class="w-full sm:w-auto justify-center !font-secondary"
                        >
                            <span wire:loading.remove wire:target="rejectReport">Reject</span>
                            <span wire:loading wire:target="rejectReport">Rejecting…</span>
                        </flux:button>
                        <flux:button
                            variant="primary"
                            wire:click="approveReport"
                            wire:loading.attr="disabled"
                            wire:target="approveReport"
                            wire:confirm="Approve and issue replacement? The new card will be created with the provided UID."
                            class="w-full sm:w-auto justify-center !font-secondary"
                        >
                            <span wire:loading.remove wire:target="approveReport">Approve & Issue Replacement</span>
                            <span wire:loading wire:target="approveReport">Processing…</span>
                        </flux:button>
                    @endif
                </div>

            </div>
        @endif
    </flux:modal>
</div>