<?php

use Livewire\Component;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Computed;

use App\Models\Card;
use App\Models\CardReport;
use App\Models\Notification;
use App\Models\UserNotification;
use App\Events\NotificationEvent;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

new #[Layout('layouts.admin-layout')] class extends Component
{
    public string $reportFilter = 'pending';
    public string $search = '';
    public string $roleFilter = ''; // '', commuter, operator

    // For the report detail modal
    public ?int $selectedReportId = null;
    public bool $show_reject_report_modal = false;
    public bool $show_approve_report_modal = false;
    public string $rejectionReason = '';

    // Store the new card UID entered in the modal
    public ?string $newCardUid = null;

    #[Computed]
    public function cardReports() {
        return CardReport::with(['user', 'card', 'approvedBy'])
            ->whereHas('user', fn($q) => $q->whereIn('role', ['operator', 'commuter']))
            ->when($this->reportFilter !== 'all', fn($q) => $q->where('status', $this->reportFilter))
            ->when($this->roleFilter, fn($q) => $q->whereHas('user', fn($q2) => $q2->where('role', $this->roleFilter)))
            ->when($this->search, function ($q) {
                $term = '%' . $this->search . '%';
                $q->where(function ($qq) use ($term) {
                    $qq->whereHas('user', function ($q2) use ($term) {
                        $q2->where('name', 'like', $term)->orWhere('user_code', 'like', $term);
                    })->orWhere('reason', 'like', $term);
                });
            })
            ->latest()
            ->get();
    }

    #[Computed]
    public function reportStats() {
        $reports = CardReport::whereHas('user', fn($q) => $q->whereIn('role', ['operator', 'commuter']));
        return [
            'total'    => (clone $reports)->count(),
            'pending'  => (clone $reports)->where('status', 'pending')->count(),
            'approved' => (clone $reports)->where('status', 'approved')->count(),
            'rejected' => (clone $reports)->where('status', 'rejected')->count(),
        ];
    }

    #[Computed]
    public function pendingReportCount() {
        return CardReport::where('status', 'pending')->count();
    }

    #[Computed]
    public function selectedReport() {
        if (!$this->selectedReportId) return null;
        return CardReport::with(['user', 'card', 'approvedBy', 'newCard'])->find($this->selectedReportId);
    }

    public function viewReport(int $reportId): void
    {
        $this->selectedReportId = $reportId;
        $this->rejectionReason = '';
        $this->newCardUid = '';
        $this->dispatch('open-report-modal');
    }

    public function approveReport(): void
    {
        $this->show_approve_report_modal = false;

        $report = CardReport::with(['card', 'user'])->findOrFail($this->selectedReportId);

        if ($report->status !== 'pending') {
            Flux::toast(variant: 'warning', duration: 4000, heading: 'Already processed.', text: 'This report has already been handled.');
            return;
        }

        $this->newCardUid = strtoupper(trim((string) $this->newCardUid));

        $this->validate([
            'newCardUid' => ['required', 'string', 'unique:cards,uid'],
        ], [
            'newCardUid.required' => 'Please tap the new blank card to capture its UID.',
            'newCardUid.regex'    => 'That doesn\'t look like a valid card tap — expected an 8-character UID. Please tap again.',
            'newCardUid.unique'   => 'A card with that UID already exists in the system.',
        ]);

        // Declare variable outside transaction so we can use it after
        $newCard = null;

        DB::transaction(function () use ($report, &$newCard) {
            $oldCard = $report->card;

            // Create the new card for the same user
            $newCard = Card::create([
                'user_id'     => $oldCard->user_id,
                'uid'         => $this->newCardUid,
                'balance'     => $oldCard->balance,
                'status'      => 'active',
                // card_number auto-generated by boot()
            ]);

            // Suspend the old card permanently (it's been physically replaced,
            // not just temporarily held — populate the same suspension fields
            // used by the manual admin suspend/reinstate flow so there's one
            // consistent audit trail either way).
            $oldCard->update([
                'status'            => 'suspended',
                'suspension_reason' => "Card reported {$report->reason} — replaced by card ending " . substr($newCard->card_number, -4) . '.',
                'suspended_at'      => now(),
                'suspended_by'      => auth()->id(),
            ]);

            // Close the report
            $report->update([
                'status'      => 'approved',
                'approved_by' => auth()->id(),
                'new_card_id' => $newCard->id,
                'approved_at' => now(),
            ]);
        });

        // Notify the commuter
        $notification = Notification::create([
            'type'    => 'Card',
            'title'   => 'Replacement Card Issued',
            'message' => 'Your lost card report has been approved. Your new card is now active and your balance has been transferred. Please collect your new card at the terminal.',
            'metadata' => [
                'report_id'   => $report->id,
                'new_card_id' => $newCard->id,
            ],
        ]);

        UserNotification::create([
            'notification_id' => $notification->id,
            'user_id'         => $report->user_id,
        ]);

        broadcast(new NotificationEvent());

        $this->selectedReportId = null;
        $this->dispatch('close-report-modal');

        Flux::toast(
            variant: 'success',
            duration: 4000,
            heading: 'Replacement issued.',
            text: 'Old card suspended. New card created with balance transferred.',
        );
    }

    public function rejectReport(): void
    {
        $this->show_reject_report_modal = false;

        $this->validate(['rejectionReason' => 'required|string|min:5|max:500'], [
            'rejectionReason.required' => 'Please provide a reason for rejection.',
            'rejectionReason.min'      => 'Reason must be at least 5 characters.',
        ]);

        $report = CardReport::findOrFail($this->selectedReportId);

        if ($report->status !== 'pending') {
            Flux::toast(variant: 'warning', duration: 4000, heading: 'Already processed.');
            return;
        }

        $report->update([
            'status'           => 'rejected',
            'approved_by'      => auth()->id(),
            'rejection_reason' => $this->rejectionReason,
            'approved_at'      => now(),
        ]);

        // Notify the commuter
        $notification = Notification::create([
            'type'    => 'Card',
            'title'   => 'Lost Card Report Rejected',
            'message' => 'Your lost card report has been rejected. Reason: ' . $this->rejectionReason . '. Please visit the terminal or contact support if you have questions.',
            'metadata' => [
                'report_id'        => $report->id,
                'rejection_reason' => $this->rejectionReason,
            ],
        ]);

        UserNotification::create([
            'notification_id' => $notification->id,
            'user_id'         => $report->user_id,
        ]);

        broadcast(new NotificationEvent());

        $this->selectedReportId = null;
        $this->rejectionReason = '';
        $this->dispatch('close-report-modal');

        Flux::toast(variant: 'success', duration: 4000, heading: 'Report rejected.', text: 'The commuter has been notified.');
    }
};
?>

<div>
    {{-- ====== PAGE HEADER (mini-navbar: heading left, notifications right) ====== --}}
    <x-page-header
        heading="Card Reports"
        description="Lost or damaged card reports from operators and commuters."
        class="mb-4"
    >
        {{-- Empty slot – no buttons inside the header --}}
    </x-page-header>

    {{-- Desktop-only action row, matching the Live Queue page's pattern --}}
    <div class="hidden sm:flex sm:items-center sm:justify-between gap-3 mb-6">
        <x-heading
            class="!font-primary !font-bold !text-light-txt-primary dark:!text-dark-txt-primary"
            style="font-size: var(--text-section-heading)"
        >
            Review and action lost or damaged card reports
        </x-heading>

        <flux:breadcrumbs class="shrink-0">
            <flux:breadcrumbs.item href="{{ route('admin.cards') }}" wire:navigate>Back to Cards</flux:breadcrumbs.item>
            <flux:breadcrumbs.item>Card Reports</flux:breadcrumbs.item>
        </flux:breadcrumbs>
    </div>

    {{-- Mobile-visible heading, since the page header above is desktop-only --}}
    <div class="sm:hidden flex items-start justify-between gap-4 mb-6">
        <div>
            <x-heading
                size="xl"
                class="!font-primary !font-bold !text-light-txt-primary dark:!text-dark-txt-primary"
                style="font-size: var(--text-page-title)"
            >
                Card Reports
            </x-heading>
            <x-text variant="subtle" class="!font-secondary mt-1 block" style="font-size: var(--text-helper)">
                Lost or damaged card reports from operators and commuters.
            </x-text>
        </div>

        <flux:breadcrumbs class="shrink-0">
            <flux:breadcrumbs.item href="{{ route('admin.cards') }}" wire:navigate>Back to Cards</flux:breadcrumbs.item>
            <flux:breadcrumbs.item>Card Reports</flux:breadcrumbs.item>
        </flux:breadcrumbs>
    </div>

    {{-- Overview stats --}}
    <div class="grid grid-cols-2 sm:grid-cols-4 gap-2 sm:gap-3 mb-6">
        <flux:card class="p-3 sm:p-4">
            <div class="flex items-center gap-1.5 sm:gap-2 mb-1.5">
                <div class="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7 rounded-lg bg-primary/10 dark:bg-primary/20 shrink-0">
                    <flux:icon.document-text class="w-3.5 h-3.5 sm:w-4 sm:h-4 text-primary dark:text-dark-txt-primary" />
                </div>
                <x-text class="font-secondary text-xs sm:text-stat-label text-light-txt-muted dark:text-dark-txt-muted">
                    Total reports
                </x-text>
            </div>
            <x-text class="font-primary text-stat-value font-bold text-light-txt-primary dark:text-dark-txt-primary block">
                {{ $this->reportStats['total'] }}
            </x-text>
        </flux:card>

        <flux:card class="p-3 sm:p-4">
            <div class="flex items-center gap-1.5 sm:gap-2 mb-1.5">
                <div class="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7 rounded-lg bg-warning/10 dark:bg-dark-warning/20 shrink-0">
                    <flux:icon.clock class="w-3.5 h-3.5 sm:w-4 sm:h-4 text-warning dark:text-dark-warning" />
                </div>
                <x-text class="font-secondary text-xs sm:text-stat-label text-light-txt-muted dark:text-dark-txt-muted">
                    Pending
                </x-text>
            </div>
            <x-text class="font-primary text-stat-value font-bold text-warning dark:text-dark-warning block">
                {{ $this->reportStats['pending'] }}
            </x-text>
        </flux:card>

        <flux:card class="p-3 sm:p-4">
            <div class="flex items-center gap-1.5 sm:gap-2 mb-1.5">
                <div class="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7 rounded-lg bg-success/10 dark:bg-dark-success/20 shrink-0">
                    <flux:icon.check-circle class="w-3.5 h-3.5 sm:w-4 sm:h-4 text-success dark:text-dark-success" />
                </div>
                <x-text class="font-secondary text-xs sm:text-stat-label text-light-txt-muted dark:text-dark-txt-muted">
                    Approved
                </x-text>
            </div>
            <x-text class="font-primary text-stat-value font-bold text-success dark:text-dark-success block">
                {{ $this->reportStats['approved'] }}
            </x-text>
        </flux:card>

        <flux:card class="p-3 sm:p-4">
            <div class="flex items-center gap-1.5 sm:gap-2 mb-1.5">
                <div class="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7 rounded-lg bg-danger/10 dark:bg-dark-danger/20 shrink-0">
                    <flux:icon.x-circle class="w-3.5 h-3.5 sm:w-4 sm:h-4 text-danger dark:text-dark-danger" />
                </div>
                <x-text class="font-secondary text-xs sm:text-stat-label text-light-txt-muted dark:text-dark-txt-muted">
                    Rejected
                </x-text>
            </div>
            <x-text class="font-primary text-stat-value font-bold text-danger dark:text-dark-danger block">
                {{ $this->reportStats['rejected'] }}
            </x-text>
        </flux:card>
    </div>

    {{-- ====== SEARCH & FILTERS (inline) ====== --}}
    <div class="flex flex-col sm:flex-row sm:items-center gap-3 mb-4">
        <div class="flex-1">
            <flux:input
                type="text"
                wire:model.live.debounce.300ms="search"
                placeholder="Search reporter name or reason…"
                class="w-full font-secondary text-table-row dark:bg-dark-secondary dark:border-dark-bd-default dark:text-dark-txt-primary"
                icon="magnifying-glass"
            />
        </div>

        <div class="flex flex-wrap sm:flex-nowrap items-stretch sm:items-center gap-2 w-full sm:w-auto">
            <flux:select
                wire:model.live="roleFilter"
                size="sm"
                class="w-full sm:w-40 font-secondary text-table-row dark:bg-dark-secondary dark:border-dark-bd-default dark:text-dark-txt-primary"
            >
                <flux:select.option value="">All users</flux:select.option>
                <flux:select.option value="commuter">Commuter</flux:select.option>
                <flux:select.option value="operator">Operator</flux:select.option>
            </flux:select>

            <flux:select
                wire:model.live="reportFilter"
                size="sm"
                class="w-full sm:w-40 font-secondary text-table-row dark:bg-dark-secondary dark:border-dark-bd-default dark:text-dark-txt-primary"
            >
                <flux:select.option value="pending">Pending</flux:select.option>
                <flux:select.option value="approved">Approved</flux:select.option>
                <flux:select.option value="rejected">Rejected</flux:select.option>
                <flux:select.option value="all">All</flux:select.option>
            </flux:select>
        </div>
    </div>

    {{-- Reports table – standard card with p-0 and sticky headers --}}
    <flux:card class="p-0! overflow-hidden">
        <div class="overflow-x-auto">
            <flux:table container:class="md:max-h-160">
                <flux:table.columns sticky class="bg-light-secondary/50 items-center bg-light-subtle/50 dark:bg-dark-secondary/50 font-secondary text-nav-label text-light-txt-muted dark:text-dark-txt-muted">
                    <flux:table.column align="center" class="hidden sm:table-cell px-1! sm:px-2! md:px-4! py-2">#</flux:table.column>
                    <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Reported by</flux:table.column>
                    <flux:table.column align="center" class="hidden md:table-cell px-1 sm:px-2 md:px-4 py-2">Role</flux:table.column>
                    <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Reason</flux:table.column>
                    <flux:table.column align="center" class="hidden md:table-cell px-1 sm:px-2 md:px-4 py-2">Submitted</flux:table.column>
                    <flux:table.column align="center" class="px-1 sm:px-2 md:px-4 py-2">Status</flux:table.column>
                    <flux:table.column align="center" class="px-1! sm:px-2! md:px-4! py-2">Actions</flux:table.column>
                </flux:table.columns>

                <flux:table.rows>
                    @forelse ($this->cardReports as $index => $report)
                        <flux:table.row :key="$report->id">
                            <flux:table.cell align="center" class="hidden sm:table-cell px-1! sm:px-2! md:px-4! py-1.5 md:py-2 font-secondary text-xs md:text-table-row text-light-txt-muted dark:text-dark-txt-muted">
                                {{ $index + 1 }}
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                                <div class="flex items-center justify-center gap-2">
                                    <flux:avatar size="xs" src="{{ $report->user->avatar_url }}" name="{{ $report->user->name }}" />
                                    <div class="text-left">
                                        <p class="font-secondary text-xs md:text-table-row font-medium text-light-txt-primary dark:text-dark-txt-primary">{{ $report->user->name }}</p>
                                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted">{{ $report->user->user_code }}</p>
                                    </div>
                                </div>
                            </flux:table.cell>

                            <flux:table.cell align="center" class="hidden md:table-cell px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                                <flux:badge size="sm" color="{{ $report->user->role === 'operator' ? 'blue' : 'amber' }}" class="font-secondary text-badge text-xs">
                                    {{ ucfirst($report->user->role) }}
                                </flux:badge>
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                                <flux:badge size="sm" color="{{ match($report->reason) { 'lost' => 'red', 'damaged' => 'yellow', default => 'zinc' } }}" class="font-secondary text-badge text-xs">
                                    {{ ucfirst($report->reason) }}
                                </flux:badge>
                            </flux:table.cell>

                            <flux:table.cell align="center" class="hidden md:table-cell px-1 sm:px-2 md:px-4 py-1.5 md:py-2 font-secondary text-xs md:text-table-row text-light-txt-muted dark:text-dark-txt-muted tabular-nums">
                                {{ $report->created_at->format('M d, Y') }}
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1 sm:px-2 md:px-4 py-1.5 md:py-2">
                                @if ($report->status === 'pending')
                                    <flux:badge color="yellow" size="sm" icon="clock" class="font-secondary text-badge text-xs">Pending</flux:badge>
                                @elseif ($report->status === 'approved')
                                    <flux:badge color="green" size="sm" icon="check-circle" class="font-secondary text-badge text-xs">Approved</flux:badge>
                                @else
                                    <flux:badge color="red" size="sm" icon="x-circle" class="font-secondary text-badge text-xs">Rejected</flux:badge>
                                @endif
                            </flux:table.cell>

                            <flux:table.cell align="center" class="px-1! sm:px-2! md:px-4! py-1.5 md:py-2">
                                <flux:button
                                    wire:click="viewReport({{ $report->id }})"
                                    variant="ghost"
                                    size="sm"
                                    icon="ellipsis-horizontal"
                                    inset="top bottom"
                                    class="scale-75 md:scale-100"
                                />
                            </flux:table.cell>
                        </flux:table.row>
                    @empty
                        <flux:table.row>
                            <flux:table.cell colspan="7" class="px-2 md:px-4 py-4">
                                <div class="flex flex-col items-center justify-center py-6 md:py-12 gap-2">
                                    <flux:icon.document-text class="w-6 h-6 md:w-8 md:h-8 text-light-txt-muted dark:text-dark-txt-muted" />
                                    <x-text class="font-secondary text-sm md:text-table-row text-light-txt-muted dark:text-dark-txt-muted">
                                        No {{ $reportFilter === 'all' ? '' : $reportFilter }} reports found.
                                    </x-text>
                                </div>
                            </flux:table.cell>
                        </flux:table.row>
                    @endforelse
                </flux:table.rows>
            </flux:table>
        </div>
    </flux:card>

    {{-- Report Detail Modal – consistent with other modals --}}
    <flux:modal
        name="report-detail-modal"
        :closable="false"
        class="w-[calc(100%-2rem)] sm:max-w-lg md:max-w-2xl mx-auto rounded-xl overflow-hidden"
        x-on:open-report-modal.window="$flux.modal('report-detail-modal').show()"
        x-on:close-report-modal.window="$flux.modal('report-detail-modal').close()"
    >
        @if ($this->selectedReport)
            @php $report = $this->selectedReport; @endphp
            <div class="flex flex-col p-4 sm:p-6 !pr-4 sm:!pr-6 space-y-5 overflow-y-auto max-h-[70vh]">

                {{-- Header --}}
                <div class="flex items-start justify-between">
                    <div>
                        <flux:heading size="xl" class="!font-primary !font-bold text-light-txt-primary dark:text-dark-txt-primary">
                            {{ ucfirst($report->user->role) }} Card Report
                        </flux:heading>
                        <flux:text class="mt-1 font-secondary text-sm text-light-txt-muted dark:text-dark-txt-muted">
                            Submitted {{ $report->created_at->format('M d, Y · h:i A') }}
                        </flux:text>
                    </div>
                    <flux:modal.close>
                        <button type="button" class="p-1 rounded-full hover:bg-light-subtle dark:hover:bg-dark-subtle text-light-txt-muted dark:text-dark-txt-muted -mt-1">
                            <flux:icon name="x-mark" class="w-5 h-5" />
                        </button>
                    </flux:modal.close>
                </div>

                {{-- Reporter info --}}
                <div class="flex items-center gap-3 p-3 rounded-lg bg-light-subtle dark:bg-dark-subtle">
                    <flux:avatar src="{{ $report->user->avatar_url }}" name="{{ $report->user->name }}" class="shrink-0" />
                    <div class="flex-1 min-w-0">
                        <p class="font-secondary text-sm font-medium text-light-txt-primary dark:text-dark-txt-primary truncate">{{ $report->user->name }}</p>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted truncate">{{ $report->user->user_code }} · {{ ucfirst($report->user->role) }}</p>
                    </div>
                    <div class="ml-auto text-right shrink-0">
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted">Card no.</p>
                        <p class="font-mono text-xs tracking-widest text-light-txt-primary dark:text-dark-txt-primary">**** {{ substr($report->card->card_number, -4) }}</p>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mt-0.5">Balance: <span class="font-medium text-light-txt-primary dark:text-dark-txt-primary">₱{{ number_format($report->card->balance, 2) }}</span></p>
                    </div>
                </div>

                {{-- Reason & status --}}
                <div class="grid grid-cols-2 gap-4">
                    <div>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mb-1">Reason</p>
                        <flux:badge size="sm" color="{{ match($report->reason) { 'lost' => 'red', 'damaged' => 'yellow', default => 'zinc' } }}" class="font-secondary text-badge text-xs">
                            {{ ucfirst($report->reason) }}
                        </flux:badge>
                    </div>
                    <div>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mb-1">Status</p>
                        @if ($report->status === 'pending')
                            <flux:badge color="yellow" size="sm" class="font-secondary text-badge text-xs">Pending</flux:badge>
                        @elseif ($report->status === 'approved')
                            <flux:badge color="green" size="sm" class="font-secondary text-badge text-xs">Approved</flux:badge>
                        @else
                            <flux:badge color="red" size="sm" class="font-secondary text-badge text-xs">Rejected</flux:badge>
                        @endif
                    </div>
                </div>

                {{-- Description --}}
                <div>
                    <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mb-1">Description</p>
                    <p class="font-secondary text-sm text-light-txt-body dark:text-dark-txt-body bg-light-subtle dark:bg-dark-subtle rounded-lg p-3">
                        {{ $report->description }}
                    </p>
                </div>

                {{-- Valid ID photo --}}
                @if ($report->valid_id_path)
                    <div>
                        <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mb-2">Valid ID submitted</p>
                        <img
                            src="{{ Storage::url($report->valid_id_path) }}"
                            alt="Valid ID"
                            class="w-full rounded-lg border border-light-bd-default dark:border-dark-bd-default object-cover max-h-52"
                        />
                    </div>
                @endif

                {{-- Approved info --}}
                @if ($report->status === 'approved')
                    <div class="rounded-lg border border-success/20 dark:border-dark-success/20 bg-success/10 dark:bg-dark-success/10 p-3 text-sm text-success dark:text-dark-success">
                        Approved by <strong>{{ $report->approvedBy?->name ?? 'Admin' }}</strong>
                        on {{ $report->approved_at?->format('M d, Y') }}.
                        New card: <span class="font-mono">**** {{ substr($report->newCard?->card_number, -4) }}</span>
                    </div>
                @endif

                {{-- Rejection info --}}
                @if ($report->status === 'rejected')
                    <div class="rounded-lg border border-danger/20 dark:border-dark-danger/20 bg-danger/10 dark:bg-dark-danger/10 p-3 text-sm text-danger dark:text-dark-danger">
                        <p class="font-medium mb-1">Rejection reason:</p>
                        <p>{{ $report->rejection_reason }}</p>
                    </div>
                @endif

                {{-- New Card UID + Rejection reason (only when pending) --}}
                @if ($report->status === 'pending')
                    <div>
                        <label class="flex items-center gap-1.5 font-secondary font-medium uppercase tracking-wide text-nav-label text-light-txt-muted dark:text-dark-txt-muted mb-1">
                            <flux:icon name="credit-card" class="w-3.5 h-3.5" />
                            New Card UID
                        </label>

                        <div class="relative">
                            {{-- Real capture field: invisible but focused, so the RFID reader's
                                 keyboard-wedge input lands here, not shown raw to the admin. --}}
                            <input
                                type="text"
                                wire:model.live.debounce.200ms="newCardUid"
                                autocomplete="off"
                                x-ref="newCardUidInput"
                                @keydown.enter.prevent
                                class="absolute inset-0 w-full h-full opacity-0 cursor-default"
                            />

                            <div
                                class="pointer-events-none rounded-lg border-2 border-dashed p-4 flex flex-col items-center justify-center text-center transition-colors
                                    {{ $newCardUid ? 'border-success dark:border-dark-success bg-success/5 dark:bg-dark-success/10' : 'border-light-bd-default dark:border-dark-bd-default' }}"
                            >
                                @if ($newCardUid)
                                    <flux:icon name="check-circle" class="w-6 h-6 text-success dark:text-dark-success mb-1" />
                                    <p class="font-mono text-base tracking-[0.3em] font-semibold text-light-txt-primary dark:text-dark-txt-primary">
                                        {{ strtoupper($newCardUid) }}
                                    </p>
                                    <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mt-1">Blank card detected</p>
                                @else
                                    <flux:icon name="wifi" class="w-6 h-6 text-light-txt-muted dark:text-dark-txt-muted mb-1 animate-pulse" />
                                    <p class="font-secondary text-sm font-medium text-light-txt-body dark:text-dark-txt-body">Waiting for the blank card's tap…</p>
                                    <p class="font-secondary text-xs text-light-txt-muted dark:text-dark-txt-muted mt-1">Please tap the new card on the reader only once.</p>
                                @endif
                            </div>
                        </div>

                        <flux:error name="newCardUid" />

                        @if ($newCardUid)
                            <button
                                type="button"
                                wire:click="$set('newCardUid', '')"
                                x-on:click="$nextTick(() => $refs.newCardUidInput.focus())"
                                class="mt-2 font-secondary text-xs text-primary hover:underline"
                            >
                                Not this card? Tap again
                            </button>
                        @endif

                        <p class="mt-1 text-xs text-light-txt-muted dark:text-dark-txt-muted">
                            This UID will be used to create a new card for the {{ $report->user->role }}.
                        </p>
                    </div>

                    <div>
                        <flux:textarea
                            wire:model="rejectionReason"
                            label="Rejection reason (required to reject)"
                            placeholder="Explain why the report is being rejected…"
                            rows="2"
                            class="font-secondary text-table-row bg-light-primary dark:bg-dark-surface text-light-txt-body dark:text-dark-txt-primary border-light-bd-default dark:border-dark-bd-default placeholder:text-light-txt-muted dark:placeholder:text-dark-txt-muted"
                        />
                    </div>
                @endif

                {{-- Action buttons --}}
                <div class="flex flex-col-reverse sm:flex-row justify-end items-stretch sm:items-center gap-2 pt-2 border-t border-light-bd-default dark:border-dark-bd-default">
                    <flux:modal.close class="w-full sm:w-auto">
                        <flux:button variant="ghost" class="w-full sm:w-auto justify-center font-secondary">
                            Close
                        </flux:button>
                    </flux:modal.close>

                    @if ($report->status === 'pending')
                        <flux:button
                            variant="danger"
                            wire:click="$set('show_reject_report_modal', true)"
                            class="w-full sm:w-auto justify-center font-secondary"
                        >
                            Reject
                        </flux:button>
                        <flux:button
                            variant="primary"
                            wire:click="$set('show_approve_report_modal', true)"
                            class="w-full sm:w-auto justify-center font-secondary"
                        >
                            Approve & Issue Replacement
                        </flux:button>
                    @endif
                </div>

            </div>
        @endif
    </flux:modal>

    {{-- Reject report confirmation --}}
    <flux:modal wire:model="show_reject_report_modal" :closable="false" class="w-[calc(100%-2rem)] max-w-xs sm:max-w-sm">
        <div class="space-y-6">
            <div>
                <flux:heading size="lg">Reject this report?</flux:heading>
                <flux:text class="mt-2">The reporter will need to re-submit their card report.</flux:text>
            </div>
            <div class="flex gap-2">
                <flux:spacer />
                <flux:modal.close>
                    <flux:button variant="ghost">Cancel</flux:button>
                </flux:modal.close>
                <flux:button wire:click="rejectReport" wire:loading.attr="disabled" wire:target="rejectReport" variant="danger">
                    <span wire:loading.remove wire:target="rejectReport">Reject</span>
                    <span wire:loading wire:target="rejectReport">Rejecting…</span>
                </flux:button>
            </div>
        </div>
    </flux:modal>

    {{-- Approve report confirmation --}}
    <flux:modal wire:model="show_approve_report_modal" :closable="false" class="w-[calc(100%-2rem)] max-w-xs sm:max-w-sm">
        <div class="space-y-6">
            <div>
                <flux:heading size="lg">Approve and issue replacement?</flux:heading>
                <flux:text class="mt-2">The new card will be created with the provided UID.</flux:text>
            </div>
            <div class="flex gap-2">
                <flux:spacer />
                <flux:modal.close>
                    <flux:button variant="ghost">Cancel</flux:button>
                </flux:modal.close>
                <flux:button wire:click="approveReport" wire:loading.attr="disabled" wire:target="approveReport" variant="primary">
                    <span wire:loading.remove wire:target="approveReport">Approve & Issue</span>
                    <span wire:loading wire:target="approveReport">Processing…</span>
                </flux:button>
            </div>
        </div>
    </flux:modal>
</div>