<?php

return [

    'ewallets' => [
        'Alipay+',
        'Bananapay Fintech Services',
        'CIS Bayad Center, Inc.',
        'DCPay (Coins.ph)',
        'Easy Pay Global EMI Corp',
        'G-Xchange, Inc.',
        'GrabPay',
        'I-Remit Inc.',
        'Lulu Financial Services',
        'Marcopay Inc.',
        'Maya Philippines, Inc.',
        'Omnipay, Inc.',
        'Peppermint Bizmoto, Inc.',
        'Philippine Digital Asset Exchange',
        'PPS-PEPP Financial Services Corporation',
        'ShopeePay Philippines, Inc.',
        'SpeedyPay Inc.',
        'Starpay Corporation',
        'Tayocash Inc.',
        'TokTok Wallet Inc.',
        'Topjuan Tech Corporation',
        'Toyota Financial Services Philippines Corporation (TFSPH)',
        'Traxion Pay Inc.',
        'USSC Money Services, Inc',
        'Wise Pilipinas, Inc.',
        'Zybi Tech Inc.',
    ],

    'banks' => [
        'AllBank (A Thrift Bank), Inc.',
        'Asia United Bank Corporation/Hello Money',
        'BDO Network Bank',
        'BDO Unibank, Inc.',
        'Bank of China',
        'Bank of Commerce',
        'Bank of the Philippine Islands / BPI Family',
        'Bayanihan Bank Inc.',
        'BPI Direct BanKo',
        'Camalig Bank, Inc. (A Rural Bank)',
        'Cantilan Bank Inc.',
        'CARD BANK Inc.',
        'CARD MRI Rizal Bank Inc.',
        'CARD SME Bank, Inc., A Thrift Bank',
        'Cebuana Lhuillier Rural Bank, Inc',
        'China Banking Corporation',
        'China Bank Savings, Inc.',
        'CIMB Philippines, Inc.',
        'City Savings Bank Inc.',
        'Community Rural Bank of Romblon, Inc.',
        'CTBC Bank (Philippines) Corporation',
        'Development Bank of the Philippines',
        'Dumaguete City Development Bank',
        'Dungganon Bank (A Rural Bank), Inc.',
        'East West Banking Corporation',
        'East West Rural Bank',
        'Equicom Savings Bank, Inc.',
        'GoTyme Bank Corporation',
        'ING Bank N.V.',
        'ISLA Bank (A Thrift Bank), Inc.',
        'Land Bank of The Philippines',
        'Legazpi Savings Bank',
        'Luzon Development Bank',
        'Malayan Bank Savings and Mortgage Bank, Inc.',
        'MariBank Philippines, Inc.',
        'MAYA BANK, INC',
        'Maybank Philippines, Inc.',
        'Metropolitan Bank and Trust Company',
        'Mindanao Consolidated Cooperative Bank',
        'OWN BANK THE RURAL BANK OF CAVITE CITY INC.',
        'Pacific Ace Savings Bank, Inc.',
        'Partner Rural Bank (Cotabato), Inc.',
        'Philippine Bank of Communications',
        'Philippine Business Bank',
        'Philippine National Bank',
        'Philippine Savings Bank',
        'Philippine Veterans Bank',
        'PhilTrust Bank',
        'Producers Savings Bank Corporation',
        'Queen City Development Bank, Inc.',
        'RANG-AY BANK A Rural Bank Inc',
        'Rizal Commercial Banking Corporation',
        'Robinsons Bank Corporation',
        'Rural Bank of Guinobatan, Inc.',
        'Security Bank Corporation',
        'Security Bank Corporation 2',
        'Southeast Country Bank, Inc. (A Rural Bank)',
        'Standard Chartered Bank',
        'Sterling Bank of Asia, Inc., A Savings Bank',
        'The Hong Kong and Shanghai Banking Corporation Limited, Philippine Branch',
        'Tonik Digital Bank',
        'Top Bank Philippines, Inc. (A Rural Bank)',
        'Union Bank of the Philippines',
        'Union Digital Bank',
        'United Coconut Planters Bank',
        'UnoBank Inc.',
        'VIGAN BANCO RURAL INCORPORADA',
        'Wealth Development Bank Corporation',
    ],

];
